services:
  - type: web
    name: etor-backend
    env: node
    plan: free
    rootDirectory: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: etor-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: etor-postgres
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: etor-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: etor-postgres
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: etor-postgres
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false

databases:
  - name: etor-postgres
    databaseName: etor
    user: etor_user
    plan: free
