services:
  - type: web
    name: etor-backend
    env: node
    plan: free
    rootDirectory: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_RX6iU4HOFnlf@ep-green-frog-agxg4c9i-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DB_HOST
        value: ep-green-frog-agxg4c9i-pooler.c-2.eu-central-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_RX6iU4HOFnlf
      - key: DB_DATABASE
        value: neondb
      - key: JWT_SECRET
        generateValue: true
      - key: FORCE_SYNC
        value: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://etor.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_FROM
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false

# Using external Neon database - no need to create PostgreSQL instance
